class Models:
    subway_stations = {
        "U1": [
            "Olympia-Einkaufszentrum",
            "Georg-Brauchle-Ring",
            "Westfriedhof",
            "Gern",
            "Rotkreuzplatz",
            "Maillingerstraße",
            "Stiglmaierplatz",
            "Hauptbahnhof",
            "Sendlinger Tor",
            "Fraunhoferstraße",
            "Kolumbusplatz",
            "Candidplatz",
            "Wettersteinplatz",
            "St.Quirin-Platz",
            "Mangfallplatz",
        ],
        "U2": [
            "Feldmoching",
            "Hasenbergl",
            "Dülferstraße",
            "Harthof",
            "Am Hart",
            "Frankfurter Ring",
            "Milbertshofen",
            "Scheidplatz",
            "Hohenzollernplatz",
            "Josephsplatz",
            "Theresienstraße",
            "Königsplatz",
            "Hauptbahnhof",
            "Sendlinger Tor",
            "Fraunhoferstraße",
            "Kolumbusplatz",
            "Silberhornstraße",
            "Untersbergstraße",
            "Giesing",
            "Karl-Preis-Platz",
            "Innsbrucker Ring",
            "Josephsburg",
            "Kreillerstraße",
            "Trudering",
            "Moosfeld",
            "Messestadt West",
            "Messestadt Ost",
        ],
        "U3": [
            "Moosach",
            "Moosacher St.-Martins-Platz",
            "Olympia-Einkaufszentrum",
            "Oberwiesenfeld",
            "Olympiazentrum",
            "Petuelring",
            "Scheidplatz",
            "Bonner Platz",
            "Münchner Freiheit",
            "Giselastraße",
            "Universität",
            "Odeonsplatz",
            "Marienplatz",
            "Sendlinger Tor",
            "Goetheplatz",
            "Poccistraße",
            "Implerstraße",
            "Brudermühlstraße",
            "Thalkirchen",
            "Obersendling",
            "Aidenbachstraße",
            "Machtlfinger Straße",
            "Forstenrieder Allee",
            "Basler Straße",
            "Fürstenried West",
        ],
        "U4": [
            "Westendstraße",
            "Heimeranplatz",
            "Schwanthalerhöhe",
            "Theresienwiese",
            "Hauptbahnhof",
            "Karlsplatz (Stachus)",
            "Odeonsplatz",
            "Lehel",
            "Max-Weber-Platz",
            "Prinzregentenplatz",
            "Böhmerwaldplatz",
            "Richard-Strauss-Straße",
            "Arabellapark",
        ],
        "U5": [
            "Laimer Platz",
            "Friedenheimer Straße",
            "Westendstraße",
            "Heimeranplatz",
            "Schwanthalerhöhe",
            "Theresienwiese",
            "Hauptbahnhof",
            "Karlsplatz (Stachus)",
            "Odeonsplatz",
            "Lehel",
            "Max-Weber-Platz",
            "Ostbahnhof",
            "Innsbrucker Ring",
            "Michaelibad",
            "Quiddestraße",
            "Neuperlach Zentrum",
            "Therese-Giehse-Allee",
            "Neuperlach Süd",
        ],
        "U6": [
            "Garching-Forschungszentrum",
            "Garching",
            "Garching-Hochbrück",
            "Fröttmaning",
            "Kieferngarten",
            "Freimann",
            "Studentenstadt",
            "Alte Heide",
            "Nordfriedhof",
            "Dietlindenstraße",
            "Münchner Freiheit",
            "Giselastraße",
            "Universität",
            "Odeonsplatz",
            "Marienplatz",
            "Sendlinger Tor",
            "Goetheplatz",
            "Poccistraße",
            "Implerstraße",
            "Harras",
            "Partnachplatz",
            "Westpark",
            "Holzapfelkreuth",
            "Haderner Stern",
            "Großhadern",
            "Klinikum Großhadern",
        ],
        "U7": [
            "Olympia-Einkaufszentrum",
            "Georg-Brauchle-Ring",
            "Westfriedhof",
            "Gern",
            "Rotkreuzplatz",
            "Maillingerstraße",
            "Stiglmaierplatz",
            "Hauptbahnhof",
            "Sendlinger Tor",
            "Fraunhoferstraße",
            "Kolumbusplatz",
            "Silberhornstraße",
            "Untersbergstraße",
            "Giesing",
            "Karl-Preis-Platz",
            "Innsbrucker Ring",
            "Michaelibad",
            "Quiddestraße",
            "Neuperlach Zentrum",
        ],
        "U8": [
            "Olympiazentrum",
            "Petuelring",
            "Scheidplatz",
            "Hohenzollernplatz",
            "Josephsplatz",
            "Theresienstraße",
            "Königsplatz",
            "Hauptbahnhof",
            "Sendlinger Tor",
            "Fraunhoferstraße",
            "Kolumbusplatz",
            "Silberhornstraße",
            "Untersbergstraße",
            "Giesing",
            "Karl-Preis-Platz",
            "Innsbrucker Ring",
            "Michaelibad",
            "Quiddestraße",
            "Neuperlach Zentrum",
        ],
    }

    connections = {}

    for line, stations in subway_stations.items():
        line_connections = []
        for i in range(len(stations) - 1):
            line_connections.append((stations[i], stations[i + 1]))
        connections[line] = line_connections

    interchange_connections = [
        ("Olympia-Einkaufszentrum (U1)", "Olympia-Einkaufszentrum (U3)"),
        ("Olympia-Einkaufszentrum (U1)", "Olympia-Einkaufszentrum (U7)"),
        ("Olympia-Einkaufszentrum (U3)", "Olympia-Einkaufszentrum (U7)"),
        ("Georg-Brauchle-Ring (U1)", "Georg-Brauchle-Ring (U7)"),
        ("Westfriedhof (U1)", "Westfriedhof (U7)"),
        ("Gern (U1)", "Gern (U7)"),
        ("Rotkreuzplatz (U1)", "Rotkreuzplatz (U7)"),
        ("Maillingerstraße (U1)", "Maillingerstraße (U7)"),
        ("Stiglmaierplatz (U1)", "Stiglmaierplatz (U7)"),
        ("Hauptbahnhof (U1)", "Hauptbahnhof (U2)"),
        ("Hauptbahnhof (U1)", "Hauptbahnhof (U4)"),
        ("Hauptbahnhof (U1)", "Hauptbahnhof (U5)"),
        ("Hauptbahnhof (U1)", "Hauptbahnhof (U7)"),
        ("Hauptbahnhof (U1)", "Hauptbahnhof (U8)"),
        ("Hauptbahnhof (U2)", "Hauptbahnhof (U4)"),
        ("Hauptbahnhof (U2)", "Hauptbahnhof (U5)"),
        ("Hauptbahnhof (U2)", "Hauptbahnhof (U7)"),
        ("Hauptbahnhof (U2)", "Hauptbahnhof (U8)"),
        ("Hauptbahnhof (U4)", "Hauptbahnhof (U5)"),
        ("Hauptbahnhof (U4)", "Hauptbahnhof (U7)"),
        ("Hauptbahnhof (U4)", "Hauptbahnhof (U8)"),
        ("Hauptbahnhof (U5)", "Hauptbahnhof (U7)"),
        ("Hauptbahnhof (U5)", "Hauptbahnhof (U8)"),
        ("Hauptbahnhof (U7)", "Hauptbahnhof (U8)"),
        ("Sendlinger Tor (U1)", "Sendlinger Tor (U2)"),
        ("Sendlinger Tor (U1)", "Sendlinger Tor (U3)"),
        ("Sendlinger Tor (U1)", "Sendlinger Tor (U6)"),
        ("Sendlinger Tor (U1)", "Sendlinger Tor (U7)"),
        ("Sendlinger Tor (U1)", "Sendlinger Tor (U8)"),
        ("Sendlinger Tor (U2)", "Sendlinger Tor (U3)"),
        ("Sendlinger Tor (U2)", "Sendlinger Tor (U6)"),
        ("Sendlinger Tor (U2)", "Sendlinger Tor (U7)"),
        ("Sendlinger Tor (U2)", "Sendlinger Tor (U8)"),
        ("Sendlinger Tor (U3)", "Sendlinger Tor (U6)"),
        ("Sendlinger Tor (U3)", "Sendlinger Tor (U7)"),
        ("Sendlinger Tor (U3)", "Sendlinger Tor (U8)"),
        ("Sendlinger Tor (U6)", "Sendlinger Tor (U7)"),
        ("Sendlinger Tor (U6)", "Sendlinger Tor (U8)"),
        ("Sendlinger Tor (U7)", "Sendlinger Tor (U8)"),
        ("Sendlinger Tor (U2)", "Sendlinger Tor (U6)"),
        ("Fraunhoferstraße (U1)", "Fraunhoferstraße (U2)"),
        ("Fraunhoferstraße (U1)", "Fraunhoferstraße (U7)"),
        ("Fraunhoferstraße (U1)", "Fraunhoferstraße (U8)"),
        ("Fraunhoferstraße (U2)", "Fraunhoferstraße (U7)"),
        ("Fraunhoferstraße (U2)", "Fraunhoferstraße (U8)"),
        ("Fraunhoferstraße (U7)", "Fraunhoferstraße (U8)"),
        ("Kolumbusplatz (U1)", "Kolumbusplatz (U2)"),
        ("Kolumbusplatz (U1)", "Kolumbusplatz (U7)"),
        ("Kolumbusplatz (U1)", "Kolumbusplatz (U8)"),
        ("Kolumbusplatz (U2)", "Kolumbusplatz (U7)"),
        ("Kolumbusplatz (U2)", "Kolumbusplatz (U8)"),
        ("Kolumbusplatz (U7)", "Kolumbusplatz (U8)"),
        ("Scheidplatz (U2)", "Scheidplatz (U3)"),
        ("Scheidplatz (U2)", "Scheidplatz (U8)"),
        ("Scheidplatz (U3)", "Scheidplatz (U8)"),
        ("Hohenzollernplatz (U2)", "Hohenzollernplatz (U8)"),
        ("Josephsplatz (U2)", "Josephsplatz (U8)"),
        ("Theresienstraße (U2)", "Theresienstraße (U8)"),
        ("Königsplatz (U2)", "Königsplatz (U8)"),
        ("Silberhornstraße (U2)", "Silberhornstraße (U7)"),
        ("Silberhornstraße (U2)", "Silberhornstraße (U8)"),
        ("Silberhornstraße (U7)", "Silberhornstraße (U8)"),
        ("Untersbergstraße (U2)", "Untersbergstraße (U7)"),
        ("Untersbergstraße (U2)", "Untersbergstraße (U8)"),
        ("Untersbergstraße (U7)", "Untersbergstraße (U8)"),
        ("Giesing (U2)", "Giesing (U7)"),
        ("Giesing (U2)", "Giesing (U8)"),
        ("Giesing (U7)", "Giesing (U8)"),
        ("Karl-Preis-Platz (U2)", "Karl-Preis-Platz (U7)"),
        ("Karl-Preis-Platz (U2)", "Karl-Preis-Platz (U8)"),
        ("Karl-Preis-Platz (U7)", "Karl-Preis-Platz (U8)"),
        ("Innsbrucker Ring (U2)", "Innsbrucker Ring (U5)"),
        ("Innsbrucker Ring (U2)", "Innsbrucker Ring (U7)"),
        ("Innsbrucker Ring (U5)", "Innsbrucker Ring (U7)"),
        ("Innsbrucker Ring (U5)", "Innsbrucker Ring (U8)"),
        ("Innsbrucker Ring (U7)", "Innsbrucker Ring (U8)"),
        ("Olympiazentrum (U3)", "Olympiazentrum (U8)"),
        ("Petuelring (U3)", "Petuelring (U8)"),
        ("Münchner Freiheit (U3)", "Münchner Freiheit (U6)"),
        ("Giselastraße (U3)", "Giselastraße (U6)"),
        ("Universität (U3)", "Universität (U6)"),
        ("Odeonsplatz (U3)", "Odeonsplatz (U4)"),
        ("Odeonsplatz (U3)", "Odeonsplatz (U5)"),
        ("Odeonsplatz (U3)", "Odeonsplatz (U6)"),
        ("Odeonsplatz (U4)", "Odeonsplatz (U5)"),
        ("Odeonsplatz (U4)", "Odeonsplatz (U6)"),
        ("Odeonsplatz (U5)", "Odeonsplatz (U6)"),
        ("Marienplatz (U3)", "Marienplatz (U6)"),
        ("Goetheplatz (U3)", "Goetheplatz (U6)"),
        ("Poccistraße (U3)", "Poccistraße (U6)"),
        ("Implerstraße (U3)", "Implerstraße (U6)"),
        ("Westendstraße (U4)", "Westendstraße (U5)"),
        ("Heimeranplatz (U4)", "Heimeranplatz (U5)"),
        ("Schwanthalerhöhe (U4)", "Schwanthalerhöhe (U5)"),
        ("Theresienwiese (U4)", "Theresienwiese (U5)"),
        ("Karlsplatz (Stachus) (U4)", "Karlsplatz (Stachus) (U5)"),
        ("Lehel (U4)", "Lehel (U5)"),
        ("Max-Weber-Platz (U4)", "Max-Weber-Platz (U5)"),
        ("Michaelibad (U5)", "Michaelibad (U7)"),
        ("Michaelibad (U5)", "Michaelibad (U8)"),
        ("Quiddestraße (U5)", "Quiddestraße (U7)"),
        ("Quiddestraße (U5)", "Quiddestraße (U8)"),
        ("Neuperlach Zentrum (U5)", "Neuperlach Zentrum (U7)"),
        ("Neuperlach Zentrum (U5)", "Neuperlach Zentrum (U8)"),
    ]

    # Weights for other edges
    edge_weights = {
        # U1 line
        ("Olympia-Einkaufszentrum (U1)", "Georg-Brauchle-Ring (U1)"): 1,
        ("Georg-Brauchle-Ring (U1)", "Westfriedhof (U1)"): 2,
        ("Westfriedhof (U1)", "Gern (U1)"): 2,
        ("Gern (U1)", "Rotkreuzplatz (U1)"): 2,
        ("Rotkreuzplatz (U1)", "Maillingerstraße (U1)"): 2,
        ("Maillingerstraße (U1)", "Stiglmaierplatz (U1)"): 1,
        ("Stiglmaierplatz (U1)", "Hauptbahnho (U1)"): 2,
        ("Hauptbahnhof (U1)", "Sendlinger Tor (U1)"): 2,
        ("Sendlinger Tor (U1)", "Fraunhoferstraße (U1)"): 1,
        ("Fraunhoferstraße (U1)", "Kolumbusplatz (U1)"): 2,
        ("Kolumbusplatz (U1)", "Candidplatz (U1)"): 1,
        ("Candidplatz (U1)", "Wettersteinplatz (U1)"): 2,
        ("Wettersteinplatz (U1)", "St.Quirin-Platz (U1)"): 1,
        ("St.Quirin-Platz (U1)", "Mangfallplatz (U1)"): 1,
        # U2 line
        ("Feldmoching (U2)" , "Hasenbergl (U2)"): 2,
        ("Hasenbergl (U2)", "Dülferstraße (U2)"): 1,
        ("Dülferstraße (U2)", "Harthof (U2)"): 1,
        ("Harthof (U2)", "Am Hart (U2)"): 1,
        ("Am Hart (U2)", "Frankfurter Ring (U2)"): 1,
        ("Frankfurter Ring(U2)", "Milbertshofen (U2)"): 2,
        ("Milbertshofen (U2)", "Scheidplatz (U2)"): 2,
        ("Scheidplatz (U2)", "Hohenzollernplatz (U2)"): 1,
        ("Hohenzollernplatz (U2)", "Josephsplatz (U2)"): 2,
        ("Josephsplatz (U2)", "Theresienstraße (U2)"): 1,
        ("Theresienstraße (U2)", "Königsplatz (U2)"): 1,
        ("Königsplatz (U2)", "Hauptbahnhof (U2)"): 2,
        ("Hauptbahnhof (U2)", "Sendlinger Tor (U2)"): 2,
        ("Sendlinger Tor (U2)", "Fraunhoferstraße (U2)"): 1,
        ("Fraunhoferstraße (U2)", "Kolumbusplatz (U2)"): 2,
        ("Kolumbusplatz (U2)", "Silberhornstraße (U2)"): 1,
        ("Silberhornstraße (U2)", "Untersbergstraße (U2)"): 1,
        ("Untersbergstraße (U2)", "Giesing (U2)"): 2,
        ("Giesing (U2)", "Karl-Preis-Platz (U2)"): 2,
        ("Karl-Preis-Platz (U2)", "Innsbrucker Ring (U2)"): 1,
        ("Innsbrucker Ring (U2)", "Josephsburg (U2)"): 2,
        ("Josephsburg (U2)", "Kreillerstraße (U2)"): 2,
        ("Kreillerstraße (U2)", "Trudering (U2)"): 2,
        ("Trudering (U2)", "Moosfeld (U2)"): 1,
        ("Moosfeld (U2)", "Messestadt West (U2)"): 2,
        ("Messestadt West (U2)", "Messestadt Ost (U2)"): 1,
        # U3 line
        ("Moosach (U3)", "Moosacher St.-Martins-Platz (U3)"): 1,
        ("Moosacher St.-Martins-Platz (U3)", "Olympia-Einkaufszentrum (U3)"): 2,
        ("Olympia-Einkaufszentrum (U3", "Oberwiesenfeld (U3"): 2,
        ("Oberwiesenfeld (U3", "Olympiazentrum (U3"): 2,
        ("Olympiazentrum (U3", "Petuelring (U3"): 1,
        ("Petuelring (U3", "Scheidplatz (U3"): 2,
        ("Scheidplatz (U3", "Bonner Platz (U3"): 1,
        ("Bonner Platz (U3", "Münchner Freiheit (U3"): 2,
        ("Münchner Freiheit (U3", "Giselastraße (U3"): 1,
        ("Giselastraße (U3", "Universität (U3"): 2,
        ("Universität (U3", "Odeonsplatz (U3"): 1,
        ("Odeonsplatz (U3", "Marienplatz (U3"): 2,
        ("Marienplatz (U3", "Sendlinger Tor (U3"): 1,
        ("Sendlinger Tor (U3", "Goetheplatz (U3"): 2,
        ("Goetheplatz (U3", "Poccistraße (U3"): 1,
        ("Poccistraße (U3", "Implerstraße (U3"): 2,
        ("Implerstraße (U3", "Brudermühlstraße (U3"): 1,
        ("Brudermühlstraße (U3", "Thalkirchen (U3"): 2,
        ("Thalkirchen (U3", "Obersendling (U3"): 1,
        ("Obersendling (U3", "Aidenbachstraße (U3"): 2,
        ("Aidenbachstraße (U3", "Machtlfinger Straße (U3"): 1,
        ("Machtlfinger Straße (U3", "Forstenrieder Allee (U3"): 2,
        ("Forstenrieder Allee (U3", "Basler Straße (U3"): 1,
        ("Basler Straße (U3)", "Fürstenried West (U3"): 1,
        # U4 line
        ("Westendstraße (U4)", "Heimeranplatz (U4"): 1,
        ("Heimeranplatz (U4", "Schwanthalerhöhe (U4)"): 1,
        ("Schwanthalerhöhe (U4)", "Theresienwiese (U4)"): 2,
        ("Theresienwiese (U4)", "Hauptbahnhof (U4)"): 1,
        ("Hauptbahnhof (U4)", "Karlsplatz (Stachus) (U4)"): 4,
        ("Karlsplatz (Stachus) (U4)", "Odeonsplatz (U4)"): 2,
        ("Odeonsplatz (U4)", "Lehel (U4)"): 1,
        ("Lehel (U4)", "Max-Weber-Platz (U4)"): 2,
        ("Max-Weber-Platz (U4)", "Prinzregentenplatz (U4)"): 1,
        ("Prinzregentenplatz (U4)", "Böhmerwaldplatz (U4)"): 2,
        ("Böhmerwaldplatz (U4)", "Richard-Strauss-Straße (U4)"): 1,
        ("Richard-Strauss-Straße (U4)", "Arabellapark (U4)"): 2,
        # U5 line
        ("Laimer Plat (U5)", "Friedenheimer Straße (U5)"): 1,
        ("Friedenheimer Straße (U5)", "Westendstraße (U5)"): 2,
        ("Westendstraße (U5)", "Heimeranplatz (U5)"): 1,
        ("Heimeranplatz (U5)", "Schwanthalerhöhe (U5)"): 1,
        ("Schwanthalerhöhe (U5)", "Theresienwiese (U5)"): 2,
        ("Theresienwiese (U5)", "Hauptbahnhof (U5)"): 1,
        ("Hauptbahnhof (U5)", "Karlsplatz (Stachus) (U5)"): 1,
        ("Karlsplatz (Stachus) (U5)", "Odeonsplatz (U5)"): 2,
        ("Odeonsplatz (U5)", "Lehel (U5)"): 1,
        ("Lehel (U5)", "Max-Weber-Platz (U5)"): 2,
        ("Max-Weber-Platz (U5)", "Ostbahnhof (U5)"): 2,
        ("Ostbahnhof (U5)", "Innsbrucker Ring (U5)"): 2,
        ("Innsbrucker Ring (U5)", "Michaelibad (U5)"): 2,
        ("Michaelibad (U5)", "Quiddestraße (U5)"): 2,
        ("Quiddestraße (U5)", "Neuperlach Zentrum (U5)"): 1,
        ("Neuperlach Zentrum (U5)", "Therese-Giehse-Allee (U5)"): 2,
        ("Therese-Giehse-Allee (U5)", "Neuperlach Süd (U5)"): 1,
        # U6 line
        ("Garching-Forschungszentrum (U6)", "Garching (U6)"): 2,
        ("Garching (U6)", "Garching-Hochbrück (U6)"): 2,
        ("Garching-Hochbrück (U6)", "Fröttmaning (U6)"): 4,
        ("Fröttmaning (U6)", "Kieferngarten (U6)"): 2,
        ("Kieferngarten (U6)", "Freimann (U6)"): 2,
        ("Freimann (U6)", "Studentenstadt (U6)"): 2,
        ("Studentenstadt (U6)", "Alte Heide (U6)"): 1,
        ("Alte Heide (U6)", "Nordfriedhof (U6)"): 1,
        ("Nordfriedhof (U6)", "Dietlindenstraße (U6)"): 2,
        ("Dietlindenstraße (U6)", "Münchner Freiheit (U6)"): 1,
        ("Münchner Freiheit (U6)", "Giselastraße (U6)"): 1,
        ("Giselastraße (U6)", "Universität (U6)"): 2,
        ("Universität (U6)", "Odeonsplatz (U6)"): 1,
        ("Odeonsplatz (U6)", "Marienplatz (U6)"): 2,
        ("Marienplatz (U6)", "Sendlinger Tor (U6)"): 1,
        ("Sendlinger Tor (U6)", "Goetheplatz (U6)"): 2,
        ("Goetheplatz (U6)", "Poccistraße (U6)"): 1,
        ("Poccistraße (U6)", "Implerstraße (U6)"): 2,
        ("Implerstraße (U6)", "Harras (U6)"): 1,
        ("Harras (U6)", "Partnachplatz (U6)"): 2,
        ("Partnachplatz (U6)", "Westpark (U6)"): 1,
        ("Westpark (U6)", "Holzapfelkreuth (U6)"): 2,
        ("Holzapfelkreuth (U6)", "Haderner Stern (U6)"): 1,
        ("Haderner Stern (U6)", "Großhadern (U6)"): 2,
        ("Großhadern (U6)", "Klinikum Großhadern (U6)"): 1,
        # U7 line
        ("Olympia-Einkaufszentrum (U7)", "Georg-Brauchle-Ring"): 1,
        ("Georg-Brauchle-Ring (U7)", "Westfriedhof"): 1,
        ("Westfriedhof (U7)", "Gern"): 2,
        ("Gern (U7)", "Rotkreuzplatz"): 2,
        ("Rotkreuzplatz (U7)", "Maillingerstraße (U7)"): 1,
        ("Maillingerstraße (U7)", "Stiglmaierplatz (U7)"): 1,
        ("Stiglmaierplatz (U7)", "Hauptbahnhof (U7)"): 2,
        ("Hauptbahnhof (U7)", "Sendlinger Tor (U7)"): 2,
        ("Sendlinger Tor (U7)", "Fraunhoferstraße (U7)"): 4,
        ("Fraunhoferstraße (U7)", "Kolumbusplatz (U7)"): 1,
        ("Kolumbusplatz (U7)", "Silberhornstraße (U7)"): 1,
        ("Silberhornstraße (U7)", "Untersbergstraße (U7)"): 2,
        ("Untersbergstraße (U7)", "Giesing (U7)"): 1,
        ("Giesing (U7)", "Karl-Preis-Platz (U7)"): 2,
        ("Karl-Preis-Platz (U7)", "Innsbrucker Ring (U7)"): 1,
        ("Innsbrucker Ring (U7)", "Michaelibad (U7)"): 2,
        ("Michaelibad (U7)", "Quiddestraße (U7)"): 2,
        ("Quiddestraße (U7)", "Neuperlach Zentrum (U7)"): 2,
        # U8 line
        ("Olympiazentrum (U8)", "Petuelring (U8)"): 1,
        ("Petuelring (U8)", "Scheidplatz (U8)"): 2,
        ("Scheidplatz (U8)", "Hohenzollernplatz (U8)"): 1,
        ("Hohenzollernplatz (U8)", "Josephsplatz (U8)"): 2,
        ("Josephsplatz (U8)", "Theresienstraße (U8)"): 1,
        ("Theresienstraße (U8)", "Königsplatz (U8)"): 2,
        ("Königsplatz (U8)", "Hauptbahnhof (U8)"): 3,
        ("Hauptbahnhof (U8)", "Sendlinger Tor (U8)"): 1,
        ("Sendlinger Tor (U8)", "Fraunhoferstraße (U8)"): 2,
        ("Fraunhoferstraße (U8)", "Kolumbusplatz (U8)"): 2,
        ("Kolumbusplatz (U8)", "Silberhornstraße (U8)"): 1,
        ("Silberhornstraße (U8)", "Untersbergstraße (U8)"): 2,
        ("Untersbergstraße (U8)", "Giesing (U8)"): 1,
        ("Giesing (U8)", "Karl-Preis-Platz (U8)"): 2,
        ("Karl-Preis-Platz (U8)", "Innsbrucker Ring (U8)"): 1,
        ("Innsbrucker Ring (U8)", "Michaelibad (U8)"): 1,
        ("Michaelibad (U8)", "Quiddestraße (U8)"): 2,
        ("Quiddestraße (U8)", "Neuperlach Zentrum (U8)"): 1,
        #Transit stations
        ("Olympia-Einkaufszentrum (U1)", "Olympia-Einkaufszentrum (U3)"): 1,
        ("Olympia-Einkaufszentrum (U1)", "Olympia-Einkaufszentrum (U7)"): 1,
        ("Olympia-Einkaufszentrum (U3)", "Olympia-Einkaufszentrum (U7)"): 1,
        ("Georg-Brauchle-Ring (U1)", "Georg-Brauchle-Ring (U7)"): 1,
        ("Westfriedhof (U1)", "Westfriedhof (U7)"): 1,
        ("Gern (U1)", "Gern (U7)"): 1,
        ("Rotkreuzplatz (U1)", "Rotkreuzplatz (U7)"): 1,
        ("Maillingerstraße (U1)", "Maillingerstraße (U7)"): 1,
        ("Stiglmaierplatz (U1)", "Stiglmaierplatz (U7)"): 1,
        ("Hauptbahnhof (U1)", "Hauptbahnhof (U2)"): 1,
        ("Hauptbahnhof (U1)", "Hauptbahnhof (U4)"): 1,
        ("Hauptbahnhof (U1)", "Hauptbahnhof (U5)"): 1,
        ("Hauptbahnhof (U1)", "Hauptbahnhof (U7)"): 1,
        ("Hauptbahnhof (U1)", "Hauptbahnhof (U8)"): 1,
        ("Hauptbahnhof (U2)", "Hauptbahnhof (U4)"): 1,
        ("Hauptbahnhof (U2)", "Hauptbahnhof (U5)"): 1,
        ("Hauptbahnhof (U2)", "Hauptbahnhof (U7)"): 1,
        ("Hauptbahnhof (U2)", "Hauptbahnhof (U8)"): 1,
        ("Hauptbahnhof (U4)", "Hauptbahnhof (U5)"): 1,
        ("Hauptbahnhof (U4)", "Hauptbahnhof (U7)"): 1,
        ("Hauptbahnhof (U4)", "Hauptbahnhof (U8)"): 1,
        ("Hauptbahnhof (U5)", "Hauptbahnhof (U7)"): 1,
        ("Hauptbahnhof (U5)", "Hauptbahnhof (U8)"): 1,
        ("Hauptbahnhof (U7)", "Hauptbahnhof (U8)"): 1,
        ("Sendlinger Tor (U1)", "Sendlinger Tor (U2)"): 1,
        ("Sendlinger Tor (U1)", "Sendlinger Tor (U3)"): 1,
        ("Sendlinger Tor (U1)", "Sendlinger Tor (U6)"): 1,
        ("Sendlinger Tor (U1)", "Sendlinger Tor (U7)"): 1,
        ("Sendlinger Tor (U1)", "Sendlinger Tor (U8)"): 1,
        ("Sendlinger Tor (U2)", "Sendlinger Tor (U3)"): 1,
        ("Sendlinger Tor (U2)", "Sendlinger Tor (U6)"): 1,
        ("Sendlinger Tor (U2)", "Sendlinger Tor (U7)"): 1,
        ("Sendlinger Tor (U2)", "Sendlinger Tor (U8)"): 1,
        ("Sendlinger Tor (U3)", "Sendlinger Tor (U6)"): 1,
        ("Sendlinger Tor (U3)", "Sendlinger Tor (U7)"): 1,
        ("Sendlinger Tor (U3)", "Sendlinger Tor (U8)"): 1,
        ("Sendlinger Tor (U6)", "Sendlinger Tor (U7)"): 1,
        ("Sendlinger Tor (U6)", "Sendlinger Tor (U8)"): 1,
        ("Sendlinger Tor (U7)", "Sendlinger Tor (U8)"): 1,
        ("Sendlinger Tor (U2)", "Sendlinger Tor (U6)"): 1,
        ("Fraunhoferstraße (U1)", "Fraunhoferstraße (U2)"): 1,
        ("Fraunhoferstraße (U1)", "Fraunhoferstraße (U7)"): 1,
        ("Fraunhoferstraße (U1)", "Fraunhoferstraße (U8)"): 1,
        ("Fraunhoferstraße (U2)", "Fraunhoferstraße (U7)"): 1,
        ("Fraunhoferstraße (U2)", "Fraunhoferstraße (U8)"): 1,
        ("Fraunhoferstraße (U7)", "Fraunhoferstraße (U8)"): 1,
        ("Kolumbusplatz (U1)", "Kolumbusplatz (U2)"): 1,
        ("Kolumbusplatz (U1)", "Kolumbusplatz (U7)"): 1,
        ("Kolumbusplatz (U1)", "Kolumbusplatz (U8)"): 1,
        ("Kolumbusplatz (U2)", "Kolumbusplatz (U7)"): 1,
        ("Kolumbusplatz (U2)", "Kolumbusplatz (U8)"): 1,
        ("Kolumbusplatz (U7)", "Kolumbusplatz (U8)"): 1,
        ("Scheidplatz (U2)", "Scheidplatz (U3)"): 1,
        ("Scheidplatz (U2)", "Scheidplatz (U8)"): 1,
        ("Scheidplatz (U3)", "Scheidplatz (U8)"): 1,
        ("Hohenzollernplatz (U2)", "Hohenzollernplatz (U8)"): 1,
        ("Josephsplatz (U2)", "Josephsplatz (U8)"): 1,
        ("Theresienstraße (U2)", "Theresienstraße (U8)"): 1,
        ("Königsplatz (U2)", "Königsplatz (U8)"): 1,
        ("Silberhornstraße (U2)", "Silberhornstraße (U7)"): 1,
        ("Silberhornstraße (U2)", "Silberhornstraße (U8)"): 1,
        ("Silberhornstraße (U7)", "Silberhornstraße (U8)"): 1,
        ("Untersbergstraße (U2)", "Untersbergstraße (U7)"): 1,
        ("Untersbergstraße (U2)", "Untersbergstraße (U8)"): 1,
        ("Untersbergstraße (U7)", "Untersbergstraße (U8)"): 1,
        ("Giesing (U2)", "Giesing (U7)"): 1,
        ("Giesing (U2)", "Giesing (U8)"): 1,
        ("Giesing (U7)", "Giesing (U8)"): 1,
        ("Karl-Preis-Platz (U2)", "Karl-Preis-Platz (U7)"): 1,
        ("Karl-Preis-Platz (U2)", "Karl-Preis-Platz (U8)"): 1,
        ("Karl-Preis-Platz (U7)", "Karl-Preis-Platz (U8)"): 1,
        ("Innsbrucker Ring (U2)", "Innsbrucker Ring (U5)"): 1,
        ("Innsbrucker Ring (U2)", "Innsbrucker Ring (U7)"): 1,
        ("Innsbrucker Ring (U5)", "Innsbrucker Ring (U7)"): 1,
        ("Innsbrucker Ring (U5)", "Innsbrucker Ring (U8)"): 1,
        ("Innsbrucker Ring (U7)", "Innsbrucker Ring (U8)"): 1,
        ("Olympiazentrum (U3)", "Olympiazentrum (U8)"): 1,
        ("Petuelring (U3)", "Petuelring (U8)"): 1,
        ("Münchner Freiheit (U3)", "Münchner Freiheit (U6)"): 1,
        ("Giselastraße (U3)", "Giselastraße (U6)"): 1,
        ("Universität (U3)", "Universität (U6)"): 1,
        ("Odeonsplatz (U3)", "Odeonsplatz (U4)"): 1,
        ("Odeonsplatz (U3)", "Odeonsplatz (U5)"): 1,
        ("Odeonsplatz (U3)", "Odeonsplatz (U6)"): 1,
        ("Odeonsplatz (U4)", "Odeonsplatz (U5)"): 1,
        ("Odeonsplatz (U4)", "Odeonsplatz (U6)"): 1,
        ("Odeonsplatz (U5)", "Odeonsplatz (U6)"): 1,
        ("Marienplatz (U3)", "Marienplatz (U6)"): 1,
        ("Goetheplatz (U3)", "Goetheplatz (U6)"): 1,
        ("Poccistraße (U3)", "Poccistraße (U6)"): 1,
        ("Implerstraße (U3)", "Implerstraße (U6)"): 1,
        ("Westendstraße (U4)", "Westendstraße (U5)"): 1,
        ("Heimeranplatz (U4)", "Heimeranplatz (U5)"): 1,
        ("Schwanthalerhöhe (U4)", "Schwanthalerhöhe (U5)"): 1,
        ("Theresienwiese (U4)", "Theresienwiese (U5)"): 1,
        ("Karlsplatz (Stachus) (U4)", "Karlsplatz (Stachus) (U5)"): 1,
        ("Lehel (U4)", "Lehel (U5)"): 1,
        ("Max-Weber-Platz (U4)", "Max-Weber-Platz (U5)"): 1,
        ("Michaelibad (U5)", "Michaelibad (U7)"): 1,
        ("Michaelibad (U5)", "Michaelibad (U8)"): 1,
        ("Quiddestraße (U5)", "Quiddestraße (U7)"): 1,
        ("Quiddestraße (U5)", "Quiddestraße (U8)"): 1,
        ("Neuperlach Zentrum (U5)", "Neuperlach Zentrum (U7)"): 1,
        ("Neuperlach Zentrum (U5)", "Neuperlach Zentrum (U8)"): 1,
    }